spring.config.import=optional:file:.env[.properties]
server.port=0

# Run one enterprise tutorial at a time: account | transfer-accounts | approve-allowance | delete-allowance | get-account-info | delete-nft-type | update-nft-type | update-nft-metadata | wipe-nft | topic
spring.profiles.active=account
